name: 'Feature Branch Sync'
description: 'Sync default branch to feature branches'
inputs:
  default-branch-name:  # id of input
    description: 'Name of default branch'
    required: true
    default: 'main'
  branches-to-exclude:  # id of input
    description: 'Branches to ignore while syncing, comma-separated'
    required: false
    default: ''
  slack-notifications:  # id of input
    description: 'Include a Slack channel webhook URL, or leave blank to disable the feature'
    required: false
    default: ''
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Branch - ${{ inputs.default-branch-name }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: feature-branch-sync.sh
      shell: bash