on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run feature branch sync
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: mgilardi/feature-branch-sync@v1
        with:
          default-branch-name: 'master'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash